export {
  CONTRACT_STATUS_LABEL,
  GRADE_LABEL, ORIENTATION_LABEL, SHAPE_LABEL,
  MEASUREMENT_FIELD_LABEL, MEASUREMENT_METHOD_LABEL,
  POLLUTANT_PHASE_LABEL, MEASUREMENT_CYCLE_LABEL,
} from "./labes";